# how to train the model(pretrain model)
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pointrcnn.yaml
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/second.yaml
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/PartA2.yaml
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/CaDDN.yaml

# how to finetune the pretrained modelpython3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/second.yaml --pretrained_model /home/ECCV-3dpruning/output/second_7862.pth --sparsity 0.5


# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/second.yaml --pretrained_model /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/second/default/ckpt/checkpoint_epoch_77.pth --sparsity 0.5
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/second.yaml --pretrained_model /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/second/default/ckpt/checkpoint_epoch_77.pth --sparsity 0.6
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/second.yaml --pretrained_model /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/second/default/ckpt/checkpoint_epoch_77.pth --sparsity 0.7
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/second.yaml --pretrained_model /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/second/default/ckpt/checkpoint_epoch_77.pth --sparsity 0.8
python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/second.yaml --pretrained_model /home/ECCV-3dpruning/output/once_second_checkpoint_epoch_77.pth --sparsity 0.5420
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint.yaml --pretrained_model /home/ECCV-3dpruning/output/once_centerpoint_checkpoint_epoch_77.pth --sparsity 0.69
python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/ECCV-3dpruning/output/once_pvrcnn_checkpoint_epoch_78.pth --sparsity 0.6067

# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/second.yaml --pretrained_model /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/second/default/ckpt/checkpoint_epoch_77.pth --sparsity 0.95



# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint.yaml --pretrained_model /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint/default/ckpt/checkpoint_epoch_77.pth --sparsity 0.4
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint.yaml --pretrained_model /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint/default/ckpt/checkpoint_epoch_77.pth --sparsity 0.5
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint.yaml --pretrained_model /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint/default/ckpt/checkpoint_epoch_77.pth --sparsity 0.6
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint.yaml --pretrained_model /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint/default/ckpt/checkpoint_epoch_77.pth --sparsity 0.7
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint.yaml --pretrained_model /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint/default/ckpt/checkpoint_epoch_77.pth --sparsity 0.8
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint.yaml --pretrained_model /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint/default/ckpt/checkpoint_epoch_77.pth --sparsity 0.9
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint.yaml --pretrained_model /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint/default/ckpt/checkpoint_epoch_77.pth --sparsity 0.95
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint.yaml --pretrained_model /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint/default/ckpt/checkpoint_epoch_77.pth --sparsity 0.99
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint.yaml --pretrained_model /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint/default/ckpt/checkpoint_epoch_77.pth --sparsity 0.99

# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:50000 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/nuscenes_models/cbgs_voxel0075_voxelnext.yaml --pretrained_model /home/ECCV-3dpruning/output/voxelnext_nuscenes_kernel1.pth --sparsity 0.16
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/second.yaml


# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn.yaml



# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/second.yaml --pretrained_model /home/ECCV-3dpruning/output/second_7862.pth --sparsity 0.95
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/second.yaml --pretrained_model /home/ECCV-3dpruning/output/second_7862.pth --sparsity 0.99
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/second.yaml --pretrained_model /home/ECCV-3dpruning/output/second_7862.pth --sparsity 0.999

# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/ECCV-3dpruning/output/pv_rcnn_8369.pth --sparsity 0.5
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/ECCV-3dpruning/output/pv_rcnn_8369.pth --sparsity 0.6
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/ECCV-3dpruning/output/pv_rcnn_8369.pth --sparsity 0.7
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/ECCV-3dpruning/output/pv_rcnn_8369.pth --sparsity 0.8
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/ECCV-3dpruning/output/pv_rcnn_8369.pth --sparsity 0.9
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/ECCV-3dpruning/output/pv_rcnn_8369.pth --sparsity 0.95
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/ECCV-3dpruning/output/pv_rcnn_8369.pth --sparsity 0.99
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/ECCV-3dpruning/output/pv_rcnn_8369.pth --sparsity 0.999

# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/voxel_rcnn_car.yaml --pretrained_model /home/output/once_models/voxel_rcnn_car/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.5
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/voxel_rcnn_car.yaml --pretrained_model /home/output/once_models/voxel_rcnn_car/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.7
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/voxel_rcnn_car.yaml --pretrained_model /home/output/once_models/voxel_rcnn_car/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.9
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/voxel_rcnn_car.yaml --pretrained_model /home/output/once_models/voxel_rcnn_car/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.95
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/voxel_rcnn_car.yaml --pretrained_model /home/output/once_models/voxel_rcnn_car/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.96
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/voxel_rcnn_car.yaml --pretrained_model /home/output/once_models/voxel_rcnn_car/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.97
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/voxel_rcnn_car.yaml --pretrained_model /home/output/once_models/voxel_rcnn_car/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.98
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/voxel_rcnn_car.yaml --pretrained_model /home/output/once_models/voxel_rcnn_car/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.99
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/voxel_rcnn_car.yaml --pretrained_model /home/output/once_models/voxel_rcnn_car/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.999



# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pointrcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pointrcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.50
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pointrcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pointrcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.70
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pointrcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pointrcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.90
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pointrcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pointrcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.95
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pointrcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pointrcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.96
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pointrcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pointrcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.97
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pointrcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pointrcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.98
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pointrcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pointrcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.99
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pointrcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pointrcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.999

# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/second.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/second/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.50
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/second.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/second/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.70
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/second.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/second/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.90
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/second.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/second/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.95
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/second.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/second/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.96
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/second.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/second/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.97
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/second.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/second/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.98
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/second.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/second/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.99
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/second.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/second/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.999

# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pv_rcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.50
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pv_rcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.70
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pv_rcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.90
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pv_rcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.95
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pv_rcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.96
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pv_rcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.97
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pv_rcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.98
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pv_rcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.99
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999 train_2d_3d.py --launcher pytorch --cfg_file /home/tools/cfgs/once_models/pv_rcnn.yaml --pretrained_model /home/output/home/tools/cfgs/once_models/pv_rcnn/default/ckpt/checkpoint_epoch_80.pth --sparsity 0.999