python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999  test.py --launcher pytorch --cfg_file /chenhao/ECCV-3dpruning/tools/cfgs/once_models/second.yaml --ckpt_dir /chenhao/ECCV-3dpruning/results_finetune_head/chenhao/ECCV-3dpruning/tools/cfgs/once_models/second/default/rd_retrain_approx/ckpt/0.4 --eval_all --eval_pruning --eval_tag 0.4
python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999  test.py --launcher pytorch --cfg_file /chenhao/ECCV-3dpruning/tools/cfgs/once_models/centerpoint.yaml --ckpt_dir /chenhao/ECCV-3dpruning/results_finetune_head/chenhao/ECCV-3dpruning/tools/cfgs/once_models/centerpoint/really/rd_retrain/ckpt/0.59 --eval_all --eval_pruning --eval_tag 0.59
python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999  test.py --launcher pytorch --cfg_file /chenhao/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn.yaml --ckpt_dir /chenhao/ECCV-3dpruning/results_finetune_head/chenhao/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn/default/rd_retrain_approx/ckpt/0.87  --eval_all --eval_pruning --eval_tag 0.87
python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999  test.py --launcher pytorch --cfg_file /chenhao/ECCV-3dpruning/tools/cfgs/once_models/centerpoint.yaml --ckpt  /chenhao/ECCV-3dpruning/output/once_centerpoint_checkpoint_epoch_77.pth
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999  test.py --launcher pytorch --cfg_file /chenhao/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn.yaml --ckpt_dir /chenhao/ECCV-3dpruning/results_finetune_head/chenhao/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn/default/rd_retrain_approx/ckpt/0.85 --eval_all --eval_pruning --eval_tag 0.80
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999  test.py --launcher pytorch --cfg_file /chenhao/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn.yaml --ckpt_dir /chenhao/ECCV-3dpruning/results_finetune_head/chenhao/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn/default/rd_retrain_approx/ckpt/0.9 --eval_all --eval_pruning --eval_tag 0.90
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999  test.py --launcher pytorch --cfg_file /chenhao/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn.yaml --ckpt_dir /chenhao/ECCV-3dpruning/results_finetune_head/chenhao/ECCV-3dpruning/tools/cfgs/once_models/pv_rcnn/default/rd_retrain_approx/ckpt/0.95 --eval_all --eval_pruning --eval_tag 0.95

# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999  test.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint.yaml --ckpt_dir /home/ECCV-3dpruning/results_finetune_head/home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint/default/rd_retrain_approx/ckpt/0.69 --eval_all --eval_pruning
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999  test.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/kitti_models/voxel_rcnn_car.yaml --ckpt_dir /home/ECCV-3dpruning/results_finetune_head/home/ECCV-3dpruning/tools/cfgs/kitti_models/voxel_rcnn_car/default/rd_retrain_approx/ckpt/0.8 --eval_all
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999  test.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/kitti_models/voxel_rcnn_car.yaml --ckpt_dir /home/ECCV-3dpruning/results_finetune_head/home/ECCV-3dpruning/tools/cfgs/kitti_models/voxel_rcnn_car/default/rd_retrain_approx/ckpt/0.9 --eval_all
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999  test.py --launcher pytorch --cfg_file /chenhao/ECCV-3dpruning/tools/cfgs/nuscenes_models/cbgs_voxel01_res3d_centerpoint.yaml --ckpt_dir  /chenhao/ECCV-3dpruning/results_finetune_head/chenhao/ECCV-3dpruning/tools/cfgs/nuscenes_models/cbgs_voxel01_res3d_centerpoint/default/rd_retrain_approx/ckpt/0.5 --eval_all --eval_pruning
# python3 -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:49999  test.py --launcher pytorch --cfg_file /home/ECCV-3dpruning/tools/cfgs/once_models/second.yaml --ckpt_dir /home/ECCV-3dpruning/output/home/ECCV-3dpruning/tools/cfgs/once_models/centerpoint/default/ckpt --eval_all

